### ISSUE TITLE
Back button?

### ISSUE THREAD

**Issue by TheWitheredStriker** [richardhbtz/soundcloud-rpc#10]
Hello. I love your application thus far! However, unless I'm doing something wrong, it seems to lack a Back button (at least on Windows 10):

![image](https://github.com/user-attachments/assets/daded723-b8f7-4648-879a-d90842a8c858)

Navigating SoundCloud with one would be a lot more efficient, hence why I opened this issue. Thanks!

(NB: There does not seem to be a shortcut either. Or at least, doing Alt + Arrow Keys does nothing)

**Comment by fuku77** [comment]
There are shortcuts for going back and forth (Ctrl+B Ctrl+F) but they seem to be broken

**Comment by TheWitheredStriker** [comment]
I see that this issue was closed. Has the problem beem fixed?
