### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by pvrzz** [richardhbtz/soundcloud-rpc#14]
This would probably be hard to do, but a dark theme for the site would be great for the client in my opinion!

**Comment by pvrzz** [comment]
of course with the option of switching between light + dark mode

**Comment by Luzefiru** [comment]
You can press <kbd>F1</kbd> to toggle dark mode.

See [this line of code](https://github.com/richardhbtz/soundcloud-rpc/blob/bdaf1743bd45ff282fb19733848b6aef07f895ea/src/main.ts#L148) together with the other controls.
