### ISSUE TITLE
Window doesn't open fully maximised

### ISSUE THREAD

**Issue by gergoreth** [richardhbtz/soundcloud-rpc#16]
When opening the app initially it isn't fully maximised but still takes up most of the screen
![Screenshot 2024-09-14 214331](https://github.com/user-attachments/assets/950653fc-de60-430f-a1fc-72047be6874c)

My display resolution is 2560x1440 if that helps at all. I'm also using multiple monitors so may be causing issues

**Comment by richardhbtz** [comment]
Fixed on 0.0.6
